[[steps]]
name = "Start MongoDB"
command = ["fluentci run --wasm mongo start"]

[[steps]]
name = "Run tests"
command = [
  "fluentci run --wasm devbox run pip install -r requirements.txt",
  "fluentci run --wasm devbox run python run.py &",
  "sleep 2",
  "fluentci run --wasm devbox run python -m unittest",
]
env = ["DB=mongodb://localhost:27017/tasks", "PORT=5000"]
